In [14]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, StandardScaler
from sklearn.model_selection import KFold, train_test_split

In [2]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

#### Dealing with missing values - Replacing missing value with mean

In [4]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

# Connect to the imputer object to the feature matrix and compute the average
imputer.fit(X[:, 1:3])

# apply the transformation; replace the missing salary with average
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [5]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

#### Encoding categorical columns: One hot encoding

One hot encoder tool if you know there is no order relationship in your<br>
categorical variable. Label Encoder  if there is indeed an order.

In [6]:
# arg1: specify that we want to encode. An encoding transformation.
# arg2: Exact name of the class that will preceed to this encoding.
# arg3: Indices of the columns we want to apply one-hot encoding.

# arg4: We want to keep the columns that won't be applied transformation;
# that won't be one hot encoded. If we don't passthrough, while applying
# the transformation, it will return only the one-hot encoded columns

transformers = [('encoder', OneHotEncoder(), [0])]
column_transformer = ColumnTransformer(transformers=transformers, remainder='passthrough')

In [7]:
# Fit_transform will return one-hot encoded matrix of features X,
# with 3 columns one hot encoded
X = np.array(column_transformer.fit_transform(X))

In [8]:
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

#### Encoding the label

In [9]:
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

In [10]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

#### Splitting dataset into training set and test set

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [12]:
X_train

array([[0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object)

In [13]:
X_test

array([[0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

#### Feature scaling

In [16]:
standard_scaler = StandardScaler()

In [18]:
X_train[:, 3:] = standard_scaler.fit_transform(X_train[:, 3:])

# Features of the test set need to be scaled by the same scaler
# that was used on the training set. If we apply fit_transform,
# on test set, we would get a new scaler.

X_test[:, 3:] = standard_scaler.transform(X_test[:, 3:])

C:\Users\Harry\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\Harry\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\Harry\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [19]:
X_train

array([[0.0, 0.0, 1.0, -0.1915918438457856, -1.0781259408412427],
       [0.0, 1.0, 0.0, -0.014117293757057902, -0.07013167641635401],
       [1.0, 0.0, 0.0, 0.5667085065333239, 0.6335624327104546],
       [0.0, 0.0, 1.0, -0.3045301939022488, -0.30786617274297895],
       [0.0, 0.0, 1.0, -1.901801144700799, -1.4204636155515822],
       [1.0, 0.0, 0.0, 1.1475343068237056, 1.2326533634535488],
       [0.0, 1.0, 0.0, 1.4379472069688966, 1.5749910381638883],
       [1.0, 0.0, 0.0, -0.7401495441200352, -0.5646194287757336]],
      dtype=object)

In [20]:
X_test

array([[0.0, 1.0, 0.0, -1.4661817944830127, -0.9069571034860731],
       [1.0, 0.0, 0.0, -0.44973664397484425, 0.20564033932253029]],
      dtype=object)